<?php
// $Id$

/**
 * @file
 * Allows administrators to add previous/next pagers to any node type.
 */


/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function flippy_theme() {
  return array(
    'flippy' => array(
      'variables' => array(
        'list' => array(),
      ),
      'template' => 'flippy',
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function flippy_form_node_type_form_alter(&$form, $form_state) {
  if (isset($form['type'])) {
    $form['flippy'] = array(
      '#type' => 'fieldset',
      '#title' => t('Flippy settings'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#group' => 'additional_settings',
    );

    $form['flippy']['flippy'] = array(
      '#type' => 'checkbox',
      '#title' => t('Build a pager for this content type'),
      '#default_value' => variable_get('flippy_' . $form['#node_type']->type, FALSE),
    );
    $form['flippy']['flippy_mode'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Pager display style'),
      '#default_value' => variable_get('flippy_mode_' . $form['#node_type']->type, array()),
      '#description' => t('After building the pager, display it in these locations.'),
      '#options' => array(
        'above' => t('Show pager above node content'),
        'below' => t('Show pager below node content'),
        'theme' => t('Add pager variables to node templates'),
        'head' => t('Add semantic previous and next links to the document HEAD.')),
      '#states' => array(
        'visible' => array(   // action to take.
          ':input[name=flippy]' => array('checked' => TRUE),
        ),
      ),
    );
  }
}

/**
 * Implements hook_node_view().
 */
function flippy_node_view($node, $view_mode = 'full') {
  if (node_is_page($node)) {
    if ($pager = variable_get('flippy_'. $node->type, NULL)) {
      $positions = variable_get('flippy_mode_' . $node->type, array());
      if (in_array('above', $positions)) {
        $node->content['flippy_top'] = array(
          '#theme' => 'flippy',
          '#weight' => -10,
          '#list' => flippy_build_list($node),
        );
      }
      if (in_array('below', $positions)) {
        $node->content['flippy_bottom'] = array(
          '#theme' => 'flippy',
          '#weight' => 10,
          '#list' => flippy_build_list($node),
        );
      }
      if (in_array('head', $positions) && node_is_page($node)) {
        $links = flippy_build_list($node);
        if (!empty($links['prev'])) {
          drupal_add_html_head_link(array(
            'rel' => 'prev',
            'href' => url('node/' . $links['prev']),
          ));
        }
        if (!empty($links['next'])) {
          drupal_add_html_head_link(array(
            'rel' => 'next',
            'href' => url('node/' . $links['next']),
          ));
        }
      }
    }
  }
}

function flippy_preprocess_node(&$vars) {
  if (node_is_page($node)) {
    if ($pager = variable_get('flippy_'. $node->type, NULL)) {
      $positions = variable_get('flippy_mode_' . $node->type, array());
      if (in_array('theme', $positions)) {
        $vars['flippy'] = flippy_build_list($node);
      }
    }
  }
}

function flippy_build_list($node) {
  $master_list = &drupal_static(__FUNCTION__);
  if (!isset($master_list)) {
    $master_list = array();
  }
  if (!isset($master_list[$node->nid])) {
    // Create a starting-point query object
    $query = db_select('node')
      ->fields('node', array('nid'))
      ->condition('nid', $node->nid, '!=')
      ->condition('type', $node->type, '=')
      ->range(0, 1);

    $first = clone $query;
    $list['first'] = $first
      ->condition('created', $node->created, '<=')
      ->orderBy('created', 'ASC')
      ->execute()->fetchField();

    $list['current'] = $node->nid;

    $prev = clone $query;
    $list['prev'] = $prev
      ->condition('created', $node->created, '<=')
      ->orderBy('created', 'DESC')
      ->execute()->fetchField();

    $next = clone $query;
    $list['next'] = $next
      ->condition('created', $node->created, '>=')
      ->orderBy('created', 'ASC')
      ->execute()->fetchField();

    $last = clone $query;
    $list['last'] = $last
      ->condition('created', $node->created, '>=')
      ->orderBy('created', 'DESC')
      ->execute()->fetchField();
    
    $master_list[$node->nid] = $list;
  }
  return $master_list[$node->nid];
}

function _flippy_nids_to_nodes(array $pager) {
  $nids = array_values($pager);
  $nodes = node_load_multiple($nids);
  foreach ($pager as $key => $nid) {
    $pager[$key] = $nodes[$nid];
  }
  return $pager;
}

function template_preprocess_flippy(&$vars) {
  drupal_add_css(drupal_get_path('module', 'flippy') . '/flippy.css');
  $nav = $vars['list'];

  $vars['first_link'] = empty($nav['first']) ? '' : l('‹ ' . t('first'), 'node/' . $nav['first']);
  $vars['previous_link'] =  empty($nav['prev']) ? '' : l('‹ ' . t('previous'), 'node/' . $nav['prev']);
  $vars['next_link'] =  empty($nav['next']) ? '' : l(t('next') . ' ›', 'node/' . $nav['next']);
  $vars['last_link'] =  empty($nav['last']) ? '' : l(t('latest') . ' ›', 'node/' . $nav['last']);
}
