<?php
// $Id: services_sessauth.module,v 1.2 2010/12/10 03:10:27 ocyrus Exp $
/**
 * @file
 *  Provides a key based validation system.
 */

/**
 * Implementation of hook_authentication_info().
 *
 * @return array
 *  The configuration array for the authentication scheme
 */
function services_sessauth_services_authentication_info() {
  return array(
    'file' => 'services_sessauth.inc',
    'title' => t('Session authentication'),
    'description' => t('The default session based authentication'),
    'authenticate_call' => '_services_sessauth_authenticate_call',
    'security_settings' => '_services_sessauth_security_settings',
    'controller_settings' => '_services_sessauth_security_settings',
  );
}


// These don't currently do anything, need to conform to new cache keys
// $cache_key = 'services:' . $endpoint_name . ':resources';
function services_sessauth_disable() {
  cache_clear_all('services:methods', 'cache');
}

function services_sessauth_enable() {
  cache_clear_all('services:methods', 'cache');
}
