<?php
// $Id$

/**
 * @file
 * Sets up a custom formatter for Link elements, outputs WebSnapr thumbnails.
 */


/**
 * Implements hook_field_formatter_info().
 */
function link_snapr_field_formatter_info() {
  return array(
    'link_snapr' => array(
      'label' => t('WebSnapr thumbnail'),
      'field types' => array('link_field'),
      'settings' => array('link_snapr_size' => ''),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function link_snapr_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $settings = $instance['display'][$view_mode]['settings'];

  $element['link_snapr_size'] = array(
    '#title' => t('Thumbnail size'),
    '#type' => 'radios',
    '#default_value' => $settings['link_snapr_size'],
    '#empty_option' => t('Unspecified (use API default)'),
    '#options' => array('T' => t("Thumbnail: 70x92"), 'S' => t("Small: 152x202")),
  );

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function link_snapr_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  if ($settings = $display['settings']) {
    switch ($settings['link_snapr_size']) {
      case 'T':
        return t('Thumbnail: 70x92');
      case 'S';
        return  t('Small: 152x202');
    }
  }

  return t('Unspecified (use API default)');
}

/**
 * Implements hook_field_formatter_view().
 *
 * Two formatters are implemented.
 * - link_snapr just outputs an image tag pointing tou WebSnapr's thumbnail
 *   generation endpoint.
 */
function link_snapr_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];

  switch ($display['type']) {
    case 'link_snapr':
      foreach ($items as $delta => $item) {
        $scheme = parse_url($item['url'], PHP_URL_SCHEME) .'://';
        $url = str_replace($scheme, '', $item['url']);
        $size = 'size='. (empty($settings['link_snapr_size']) ? 'S' : $settings['link_snapr_size']) . '&';

        $variables = array(
          'path' => 'http://images.websnapr.com/?' .$size. 'url='. urlencode($url), 
          'alt' => empty($item['title'] )? $item['url'] : $item['title'],
          'title' => empty($item['title'] )? $item['url'] : $item['title'],
          'width' => ($settings['link_snapr_size'] == 'T') ? 92 : 202,
          'height' => ($settings['link_snapr_size'] == 'T') ? 70: 152,
        );
        $img = theme('image', $variables);
        $element[$delta]['#markup'] = l($img, $item['url'], array('html' => TRUE, 'attributes' => $item['attributes']));
      }
      break;
  }

  return $element;
}